// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/work/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/contact" | "/work/:slug";
  };
  "./layouts/PageLayout.tsx": {
    id: "layouts/PageLayout";
    page: "/" | "/about" | "/contact" | "/work/:slug";
  } | {
    id: "home-view";
    page: "/";
  } | {
    id: "about-view";
    page: "/about";
  } | {
    id: "contact-view";
    page: "/contact";
  } | {
    id: "project-view";
    page: "/work/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "layouts/PageLayout": typeof import("./src/./layouts/PageLayout.tsx");
  "home-view": typeof import("./src/./layouts/PageLayout.tsx");
  "about-view": typeof import("./src/./layouts/PageLayout.tsx");
  "contact-view": typeof import("./src/./layouts/PageLayout.tsx");
  "project-view": typeof import("./src/./layouts/PageLayout.tsx");
};