// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/projects/:slug";
  };
  "./layouts/PageLayout.tsx": {
    id: "home-index";
    page: "/";
  } | {
    id: "project-slug";
    page: "/projects/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "home-index": typeof import("./src/./layouts/PageLayout.tsx");
  "project-slug": typeof import("./src/./layouts/PageLayout.tsx");
};